# Generated by Django 3.0.5 on 2020-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=20)),
                ('cronpattern', models.CharField(max_length=10)),
                ('frequency', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
